language: php
sudo: false

php:
    - 7.0
    - 7.1

before_script:
    # Update composer first
    - travis_retry composer self-update
    # Install dependancies
    - travis_retry composer install --no-interaction
    # Install extra dependancies for Code Climate
    - travis_retry composer require codeclimate/php-test-reporter:@dev --prefer-source

script:
    - mkdir -p build/logs
    - phpunit

after_script:
    - travis_retry php src/vendor/bin/test-reporter
